name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tailwindcss-update:
    name: Generate Tailwind CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: assets/app-tailwind.css
          output: assets/app.css
          params: ""
      - name: Commit & Push
        run: |
          git add --force assets/app.css
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -m "ci: tailwindcss-update"
          git push
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
  theme-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Replace with the version you need
          bundler-cache: true

      # Install Theme Check locally
      - name: Install Theme Check
        run: gem install theme-check --user-install

      # Add local gem path to PATH
      - name: Add gem install path to PATH
        run: echo "::add-path::$HOME/.gem/ruby/$(ruby -e 'print RUBY_VERSION')/bin"

      # Run Theme Check
      - name: Run Theme Check
        run: theme-check